spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://postgres_app:5432/postgres
    username: postgres
    password: postgres
  profiles:
    active: production
  application:
    name: shop-app
  h2:
    console:
      enabled: true
server:
  port: 8086